restaurant/urls.py
from django.urls import path

from .views import (
    index,
    login,
    sign_up,
    CookListView,
    CookDetailView,
    CookCreateView,
    CookUpdateView,
    CookDeleteView,
    DishListView,
    DishDetailView,
    DishCreateView,
    DishUpdateView,
    DishDeleteView,
    DishTypeListView,
    DishTypeDetailView,
    DishTypeCreateView,
    DishTypeUpdateView,
    DishTypeDeleteView,
    DishAssignCookView,
    IngredientListView,
    IngredientCreateView,
    IngredientsForDishView,
    IngredientDetailView,
    IngredientUpdateView,
    IngredientDeleteView,
)

urlpatterns = [
    path("", index, name="index"),
    path("register/", sign_up, name="register"),
    path("login/", login, name="login"),
    # path('logout/', log_out, name='logout'),
    # path('register/', sign_up, name='register'),
    path(
        "cooks/",
        CookListView.as_view(),
        name="cook-list",
    ),
    path("cooks/<int:pk>/", CookDetailView.as_view(), name="cook-detail"),
    path("cooks/create", CookCreateView.as_view(), name="cook-form"),
    path("cooks/<int:pk>/update", CookUpdateView.as_view(), name="cook-form"),
    path("cooks/<int:pk>/delete", CookDeleteView.as_view(), name="cook-confirm-delete"),
    path("dishes/", DishListView.as_view(), name="dish-list"),
    path("dishes/<int:pk>/", DishDetailView.as_view(), name="dish-detail"),
    path("dishes/<int:pk>/update", DishUpdateView.as_view(), name="dish-form"),
    path("dishes/create", DishCreateView.as_view(), name="dish-form"),
    path(
        "dishes/<int:pk>/delete", DishDeleteView.as_view(), name="dish-confirm-delete"
    ),
    path("dishtypes/", DishTypeListView.as_view(), name="dishtype-list"),
    path("dishtypes/<int:pk>/", DishTypeDetailView.as_view(), name="dishtype-detail"),
    path("dishtypes/create", DishTypeCreateView.as_view(), name="dishtype-form"),
    path(
        "dishtypes/<int:pk>/delete",
        DishTypeDeleteView.as_view(),
        name="dishtype-confirm-delete",
    ),
    path(
        "dishtypes/<int:pk>/update", DishTypeUpdateView.as_view(), name="dishtype-form"
    ),
    path("ingredients/", IngredientListView.as_view(), name="ingredient-list"),
    path("ingredients/create", IngredientCreateView.as_view(), name="ingredient-form"),
    path(
        "ingredients/<int:pk>", IngredientDetailView.as_view(), name="ingredient-detail"
    ),
    path(
        "ingredients/<int:pk>/update",
        IngredientUpdateView.as_view(),
        name="ingredient-form",
    ),
    path(
        "ingredients/<int:pk>/delete",
        IngredientDeleteView.as_view(),
        name="ingredient-confirm-delete",
    ),
    path(
        "dishes/<int:pk>/ingredients/",
        IngredientsForDishView.as_view(),
        name="ingredients-for-dish",
    ),
    path(
        "dishes/<int:pk>/assign-me/",
        DishAssignCookView.as_view(),
        name="dish-assign-cook",
    ),
]

app_name = "restaurant"

restaurant_kitchen_service/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("restaurant.urls", namespace="restaurant")),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

restaurant/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, User


class DishType(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Cook(AbstractUser):
    years_of_experience = models.IntegerField(default=0)


class Ingredient(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Dish(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    dish_type = models.CharField(max_length=100)
    cooks = models.ManyToManyField(Cook, blank=True)
    ingredients = models.ManyToManyField(
        Ingredient, through="DishIngredient", related_name="dishes"
    )

    def __str__(self):
        return self.name

    @property
    def available_cooks(self):
        return Cook.objects.exclude(
            pk__in=self.cooks.all().values_list("pk", flat=True)
        )


class DishIngredient(models.Model):
    dish = models.ForeignKey(Dish, on_delete=models.CASCADE)
    ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE)

restaurant/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from .models import Ingredient, Dish, Cook, DishType


class DishForm(forms.ModelForm):
    ingredients = forms.ModelMultipleChoiceField(
        queryset=Ingredient.objects.all(), widget=forms.CheckboxSelectMultiple
    )
    dish_type = forms.ModelChoiceField(queryset=DishType.objects.all())

    class Meta:
        model = Dish
        fields = ("name", "dish_type", "description", "price", "ingredients")


class DishAssignCookForm(forms.ModelForm):
    cooks = forms.ModelMultipleChoiceField(
        queryset=Cook.objects.all(),
      )

    class Meta:
        model = Dish
        fields = ["cooks"]

    def clean(self):
        cleaned_data = super().clean()
        cooks = cleaned_data.get("cooks")
        if not cooks:
            raise forms.ValidationError("Please select at least one cook.")


class CookSearchForm(forms.Form):
    name = forms.CharField(
        max_length=150,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by username:"}),
    )


class DishSearchForm(forms.Form):
    name = forms.CharField(
        max_length=150,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by dish name:"}),
    )


class DishTypeSearchForm(forms.Form):
    name = forms.CharField(
        max_length=150,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by dish type name:"}),
    )


class IngredientSearchForm(forms.Form):
    name = forms.CharField(
        max_length=150,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by ingredient name:"}),
    )


class LoginForm(forms.Form):
    username = forms.CharField(max_length=65)
    password = forms.CharField(max_length=65, widget=forms.PasswordInput)


class RegisterForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(UserCreationForm, self).__init__(*args, **kwargs)

        for fieldname in ["username", "password1", "password2"]:
            self.fields[fieldname].help_text = None

    class Meta:
        model = Cook
        fields = ["username", "email", "password1", "password2"]

restaurant/views.py
from django.contrib.auth import login as dj_login
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.urls import reverse_lazy
from django.views import generic, View
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import RedirectView

from .forms import (
    LoginForm,
    RegisterForm,
    CookSearchForm,
    DishForm,
    DishAssignCookForm,
    DishSearchForm,
    DishTypeSearchForm,
    IngredientSearchForm,
)

from .models import DishType, Dish, Cook, Ingredient


def login(request):
    """View function for the register page of the site."""
    context = {"login": LoginForm()}
    return render(request, "registration/login.html", context=context)


def sign_up(request):
    if request.method == "GET":
        form = RegisterForm()
        return render(request, "registration/register.html", {"form": form})

    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()
            messages.success(request, "You have singed up successfully.")
            dj_login(request, user)
            return redirect("restaurant:login")
        else:
            return render(request, "registration/register.html", {"reg_form": form})


@login_required
def index(request):
    """View function for the home page of the site."""

    num_cooks = Cook.objects.count()
    num_dishes = Dish.objects.count()
    num_dishtypes = DishType.objects.count()
    num_ingredients = Ingredient.objects.count()

    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1

    context = {
        "num_cooks": num_cooks,
        "num_dishes": num_dishes,
        "num_dishtypes": num_dishtypes,
        "num_ingredients": num_ingredients,
        "num_visits": num_visits + 1,
    }

    return render(request, "restaurant/index.html", context=context)


class CookListView(generic.ListView):
    model = Cook
    context_object_name = "cooks"
    template_name = "restaurant/cook_list.html"
    paginate_by = 5

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["search_form"] = CookSearchForm()
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        name = self.request.GET.get("name")
        if name:
            queryset = queryset.filter(username__icontains=name)
        return queryset


class CookDetailView(LoginRequiredMixin, generic.DetailView):
    model = Cook
    context_object_name = "cook"
    template_name = "restaurant/cook_detail.html"
    success_url = reverse_lazy("restaurant:cook-list")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["dishes"] = Dish.objects.filter(cooks=self.object)
        return context


class CookCreateView(LoginRequiredMixin, generic.CreateView):
    model = Cook
    fields = [
        "years_of_experience",
        "username",
        "email",
        "password",
        "first_name",
        "last_name",
        "is_staff",
        "is_active",
        "is_superuser",
    ]
    template_name = "restaurant/cook_form.html"
    success_url = reverse_lazy("restaurant:cook-list")


class CookUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Cook
    fields = "__all__"
    success_url = reverse_lazy("restaurant:cook-list")


class CookDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Cook
    fields = "__all__"
    success_url = reverse_lazy("restaurant:cook-list")


class DishListView(LoginRequiredMixin, generic.ListView):
    model = Dish
    context_object_name = "dishes"
    template_name = "restaurant/dish_list.html"
    paginate_by = 5

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["search_form"] = DishSearchForm()
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        name = self.request.GET.get("name")
        if name:
            queryset = queryset.filter(name__icontains=name)
        return queryset


class DishCreateView(LoginRequiredMixin, generic.CreateView):
    model = Dish
    form_class = DishForm
    template_name = "restaurant/dish_form.html"
    success_url = reverse_lazy("restaurant:dish-list")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["available_dish_types"] = DishType.objects.all()
        return context


class DishDetailView(LoginRequiredMixin, generic.DetailView):
    model = Dish
    template_name = "restaurant/dish_detail.html"
    success_url = reverse_lazy("restaurant:dish-list")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["assign_cook_form"] = DishAssignCookForm()
        context["all_cooks"] = Cook.objects.all()
        return context


class DishUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Dish
    fields = "__all__"
    success_url = reverse_lazy("restaurant:dish-list")


class DishDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Dish
    success_url = reverse_lazy("restaurant:dish-list")


class DishTypeListView(LoginRequiredMixin, generic.ListView):
    model = DishType
    context_object_name = "dishtypes"
    template_name = "restaurant/dishtype_list.html"
    paginate_by = 5

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["search_form"] = DishTypeSearchForm()
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        name = self.request.GET.get("name")
        if name:
            queryset = queryset.filter(name__icontains=name)
        return queryset


class DishTypeDetailView(LoginRequiredMixin, generic.DetailView):
    model = DishType
    context_object_name = "dish_type"
    template_name = "restaurant/dishtype_detail.html"
    success_url = reverse_lazy("restaurant:dishtype_list")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["dishes"] = Dish.objects.filter(dish_type=self.object)
        return context


class DishTypeCreateView(LoginRequiredMixin, generic.CreateView):
    model = DishType
    fields = "__all__"
    template_name = "restaurant/dishtype_form.html"
    success_url = reverse_lazy("restaurant:dishtype-list")


class DishTypeUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = DishType
    fields = "__all__"
    success_url = reverse_lazy("restaurant:dishtype-list")


class DishTypeDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = DishType
    success_url = reverse_lazy("restaurant:dishtype-list")


class IngredientListView(LoginRequiredMixin, generic.ListView):
    model = Ingredient
    context_object_name = "ingredients"
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["search_form"] = IngredientSearchForm()
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        name = self.request.GET.get("name")
        if name:
            queryset = queryset.filter(name__icontains=name)
        return queryset


class IngredientDetailView(LoginRequiredMixin, generic.DetailView):
    model = Ingredient
    template_name = "restaurant/ingredient_detail.html"
    context_object_name = "ingredient"


class IngredientCreateView(LoginRequiredMixin, generic.CreateView):
    model = Ingredient
    fields = "__all__"
    success_url = reverse_lazy("restaurant:ingredient-list")


class IngredientUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Ingredient
    fields = "__all__"
    success_url = reverse_lazy("restaurant:ingredient-list")


class IngredientDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Ingredient
    success_url = reverse_lazy("restaurant:ingredient-list")


class IngredientsForDishView(View):
    def get(self, request, *args, **kwargs):
        dish = get_object_or_404(Dish, pk=kwargs["pk"])
        ingredients = dish.ingredients.all()
        context = {"dish": dish, "ingredients": ingredients}
        return render(request, "restaurant/dish_detail.html", context)


class DishAssignCookView(LoginRequiredMixin, RedirectView):
    url = reverse_lazy("restaurant:dish-list")

    def post(self, request, *args, **kwargs):
        dish = get_object_or_404(Dish, pk=self.kwargs["pk"])
        cook_id = request.POST.get("cook_id")
        if cook_id:
            try:
                cook = Cook.objects.get(pk=cook_id)
            except Cook.DoesNotExist:
                messages.error(request, "Selected cook does not exist")
            else:
                if cook in dish.cooks.all():
                    dish.cooks.remove(cook)
                    messages.success(
                        request,
                        f"Cook {cook} no more responsible for {dish.name}",
                        extra_tags="alert alert-danger",
                    )
                else:
                    dish.cooks.add(cook)
                    messages.success(
                        request,
                        f"{dish.name} has been assigned to cook {cook} ",
                        extra_tags="alert alert-success",
                    )
        else:
            messages.error(request, "No cook was selected")
        return super().post(request, *args, **kwargs)

templates/restaurant/cook_confirm_delete.html
{% extends "base_presentation.html" %}

{% block content %}
  <h1>Delete the cook?</h1>
  <p>Are you sure you really want to delete this cook?</p>
  <p><strong>All cook`s dependencies will also be deleted!</strong></p>
  <form action="" method="post" novalidate>
    {% csrf_token %}

    <input type="submit" value="Yes, Delete this cook" class="btn btn-danger">
  </form>
{% endblock %}

templates/restaurant/cook_form.html
{% extends "base_presentation.html" %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} cook</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-outline-secondary">
  </form>

{% endblock %}

templates/restaurant/cook_list.html
{% extends "base_presentation.html" %}
{% load crispy_forms_filters %}

{% block content %}

    <form class="navbar-search form-inline" id="navbar-search-main">
      <div class="input-group input-group-merge search-bar">

          <form action="" method="get" class="form-inline">
            {{ search_form|crispy }}
            <input class="btn btn-secondary " type="submit" value="&#128269;">
          </form>

      </div>
    </form>
  <br>
  <br>
  <h1>Cooks List
    <a href="{% url 'restaurant:cook-form' %}" class="btn btn-outline-primary link-to-page">
      + new cook
    </a>
  </h1>

  <br>
  <br>
  {% if cooks %}
    <table class="table">
      <thead>
        <tr>
          <th>ID</th>
          <th>Username</th>
          <th>First name</th>
          <th>Last name</th>
          <th>Update</th>
          <th>Delete</th>
        </tr>
      </thead>
      <tbody>
        {% for cook in cooks %}
          <tr>
            <td>{{ cook.id }}</td>
            <td>
              <a style="color: saddlebrown" href="{% url 'restaurant:cook-detail' pk=cook.id %}">
                {{ cook.username }}
                {% if user == cook %} (Me){% endif %}
              </a>
            </td>
            <td>{{ cook.first_name }}</td>
            <td>{{ cook.last_name }}</td>
            <td>
              <a href="{% url 'restaurant:cook-form' pk=cook.id %}" >
                UPDATE
              </a>
            </td>
            <td>
              <a style="color: red" href="{% url 'restaurant:cook-confirm-delete' pk=cook.id %}">
                DELETE
              </a>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p>There are no cooks in the service.</p>
  {% endif %}
{% endblock %}

templates/restaurant/dish_form.html
{% extends "base_presentation.html" %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block content %}
  <h1>{{ object|yesno:"Update, Create" }} dish</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
      <br>
      <br>
    <input type="submit" value="Submit" class="btn btn-outline-secondary">


  </form>

{% endblock %}

templates/restaurant/dish_type_list.html
{% extends "base.html" %}

{% block content %}
  <h1>
    List of Dish Types
    <a href="{% url 'restaurant:dish-type-form' %}" class="btn btn-outline-primary link-to-page">
      + new dish type
    </a>
  </h1>

  {% if dish_types %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Name</th>

      </tr>

      {% for dish in dish_types %}
        <tr>
          <td>
              {{ dish.id }}
          </td>
          <td>
              {{ dish.name }}
          </td>

          <td>
{#              <a href="{% url 'restaurant:dish-update' pk=dish.id %}">#}
{#                Update#}
{#              </a>#}
{#            </td>#}
{#            <td>#}
{#              <a style="color: red"#}
{#                href="{% url 'restaurant:dish-type-delete' pk=dish.id %}">#}
{#                DELETE#}
{#              </a>#}
{#            </td>#}
        </tr>
      {% endfor %}
    </table>

  {% else %}
      <p>There are no dish types in the kitchen service list .</p>
  {% endif %}
{% endblock %}

templates/restaurant/dishtype_confirm_delete.html
{% extends "base_presentation.html" %}

{% block content %}
  <h1>Delete the type of dishes?</h1>
  <p>Are you sure you really want to delete this type of dishes?</p>
  <p><strong>All dependencies will also be deleted!</strong></p>
  <form action="" method="post" novalidate>
    {% csrf_token %}

    <input type="submit" value="Yes, Delete this dish type" class="btn btn-danger">
  </form>
{% endblock %}

templates/restaurant/dishtype_detail.html
{% extends "base_presentation.html" %}

{% block content %}
  <h1>
    Type of Dishes: {{ dish_type.name }}
  </h1>

  <p>{{ dishtype.description }}</p>
  <h2>All dishes of this dish type</h2>
  <ul>
    {% for dish in dishes %}
      <li style="color: chocolate">{{ dish.name }} </li>
    {% empty %}
      <li>No dishes for this dishtype</li>
    {% endfor %}
  </ul>



{% endblock %}

templates/restaurant/dishtype_list.html
{% extends "base_presentation.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <form class="navbar-search form-inline" id="navbar-search-main">
      <div class="input-group input-group-merge search-bar">

          <form action="" method="get" class="form-inline">
            {{ search_form|crispy }}
            <input class="btn btn-secondary " type="submit" value="&#128269;">
          </form>

      </div>
    </form>
  <br>
  <br>
  <h1>
    List of Dish Types
    <a href="{% url 'restaurant:dishtype-form' %}" class="btn btn-outline-primary link-to-page">
      + new dish type
    </a>
  </h1>
  <br>
  <br>
{#  <form action="" method="get" class="form-inline">#}
{#      {{ search_form|crispy }}#}
{#      <input class="btn btn-secondary " type="submit" value="&#128269;">#}
{#  </form>#}
  <br>
  <br>
  {% if dishtypes %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>UPDATE</th>
        <th>DELETE</th>

      </tr>

      {% for dishtype in dishtypes %}
        <tr>
          <td>
              {{ dishtype.id }}
          </td>
          <td>
             <a style="color: saddlebrown "href="{% url 'restaurant:dishtype-detail' pk=dishtype.id %}">
                 {{ dishtype.name }}
              </a>

          </td>

          <td>
              <a href="{% url 'restaurant:dishtype-form' pk=dishtype.id %}">
                UPDATE
              </a>
          </td>

          <td>
              <a style="color: red"
                href="{% url 'restaurant:dishtype-confirm-delete' pk=dishtype.id %}">
                DELETE
              </a>
          </td>
        </tr>
      {% endfor %}
    </table>

  {% else %}
      <p>There are no dish types in the kitchen service list.</p>
  {% endif %}
{% endblock %}

templates/restaurant/ingredient_confirm_delete.html
{% extends "base_presentation.html" %}

{% block content %}
  <h1>Delete this ingredient?</h1>
  <p>Are you sure you really want to delete this ingredient?</p>
  <p><strong>All ingredients`s dependencies will also be deleted!</strong></p>
  <form action="" method="post" novalidate>
    {% csrf_token %}

    <input type="submit" value="Yes, Delete this ingredient" class="btn btn-danger">
  </form>
{% endblock %}

templates/restaurant/ingredient_detail.html
{% extends "base_presentation.html" %}
{% block content %}

<h2>Name: {{ ingredient.name }}</h2>

  <h3>Dishes with this ingredient:</h3>
<ul>
{% for dish in ingredient.dishes.all %}
    <li style="color: chocolate">{{ dish }}</li>
{% endfor %}
</ul>
{% endblock %}

templates/restaurant/ingredient_form.html
{% extends "base_presentation.html" %}
{% load crispy_forms_filters %}
<h1>New Dish Ingredient</h1>

{% block content %}
  <h1>{{ object|yesno:"Update, Create" }} dish ingredient</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-outline-secondary">
  </form>
   <form>
    <ul>
      {% for ingredient in form.ingredients %}
        <li>
          {{ ingredient }}
          {% if ingredient.value %}
            (<a href="{% url 'restaurant:ingredient-dishes' ingredient.value %}">view dishes</a>)
          {% endif %}
        </li>
      {% endfor %}
    </ul>


  </form>
{% endblock %}

templates/restaurant/ingredient_list.html
{% extends "base_presentation.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <form class="navbar-search form-inline" id="navbar-search-main">
      <div class="input-group input-group-merge search-bar">

          <form action="" method="get" class="form-inline">
            {{ search_form|crispy }}
            <input class="btn btn-secondary " type="submit" value="&#128269;">
          </form>

      </div>
    </form>
  <br>
  <br>
    <h1>Ingredient List

      <a href="{% url 'restaurant:ingredient-form' %}" class="btn btn-outline-primary link-to-page">
        + new ingredient
      </a>
   </h1>
  <br>
  <br>
{#   <form action="" method="get" class="form-inline">#}
{#      {{ search_form|crispy }}#}
{#      <input class="btn btn-secondary " type="submit" value="&#128269;">#}
{#  </form>#}
  <br>
  <br>


    {% if ingredients %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Part of which dish: </th>
        <th>UPDATE</th>
        <th>DELETE</th>

      </tr>
    {% for ingredient in ingredients %}
      <tr>
        <td>{{ ingredient.id }}</td>
        <td><a style="color: saddlebrown" href="{% url 'restaurant:ingredient-detail' pk=ingredient.id %}">{{ ingredient.name }} </a></td>
        <td>
          {% for dish in ingredient.dishes.all %}
            {{ dish.name }}{% if not forloop.last %}, {% endif %}
          {% empty %}
            None
          {% endfor %}
        </td>
        <td><a  href="{% url 'restaurant:ingredient-form' pk=ingredient.id %}">UPDATE</a></td>
        <td><a style="color: red" href="{% url 'restaurant:ingredient-confirm-delete' pk=ingredient.id %}">DELETE</a></td>
      </tr>
    {% endfor %}

    </table>
    {% else %}
      <p>There are no ingredients in the service.</p>
    {% endif %}
{% endblock %}